"""Intersectional disparate impact and a less-discriminatory-alternative search.

`train.py` section 8 reports AIR, the score distribution and the proxy ablation
for ONE binary attribute. Two things were missing and this closes both:

  1. the cross of two attributes, where a cell can fail while both marginals pass
  2. the doctrinal step after "the model has business necessity": whether a LESS
     DISCRIMINATORY ALTERNATIVE serves the same purpose comparably well

Writes docs/FAIRNESS_DEEP.md.

    python run_fairness_deep.py
"""
from __future__ import annotations

import pickle
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src import fairness
from src.imbalance import make_model
from src.intersectional import format_table, intersectional_table

SUSPECTED_PROXIES = ["mcc_risk", "cross_border"]
AUC_TOLERANCE = 0.005
AIR_MIN_GAIN = 0.010


def _fit_score(X_tr, y_tr, X_te, cols, features):
    idx = [features.index(c) for c in cols]
    m = make_model(seed=0, features=cols, monotone=True)
    pos = max(int(y_tr.sum()), 1)
    w = np.where(y_tr == 1, (len(y_tr) - pos) / pos, 1.0)
    m.fit(X_tr[:, idx], y_tr, sample_weight=w)
    return m.predict_proba(X_te[:, idx])[:, 1]


def main() -> None:
    art = pickle.load((ROOT / "artifacts" / "model.pkl").open("rb"))
    features = list(art["features"])
    X_tr = np.asarray(art["reference_X"], dtype=float)
    y_tr = np.asarray(art["reference_y"], dtype=int)
    X_te = np.asarray(art["holdout_X"], dtype=float)
    y_te = np.asarray(art["holdout_y"], dtype=int)
    df_te = pd.DataFrame(X_te, columns=features)

    score = art["model"].predict_proba(X_te)[:, 1]
    if art.get("calibrator") is not None:
        score = art["calibrator"].predict(score)
    thr = float(art["threshold"])
    approved = score < thr

    # Two attributes, correlated with different features, so the cross is not a
    # relabelling of one of them.
    group_a = fairness.synthesize_protected_attribute(
        df_te, {"card_tenure_days": -0.5, "mcc_risk": 0.4}, seed=17)
    group_b = fairness.synthesize_protected_attribute(
        df_te, {"amount_minor": 0.45, "cross_border": 0.35}, seed=23)

    out = []
    add = out.append
    add("# ML-1 -- intersectional impact and the alternative search")
    add("")
    add("Generated by `run_fairness_deep.py`. Both protected attributes are")
    add("**synthetic overlays constructed by this repo** -- they are correlated")
    add("with real features on purpose so the machinery has something to find,")
    add("and no result here describes a real population.")
    add("")
    add("## 1. One attribute at a time, then the cross")
    add("")
    add("```")
    res = intersectional_table(approved, group_a, group_b,
                               name_a="tenure_proxy", name_b="amount_proxy")
    add(format_table(res))
    add("```")
    add("")
    add("Correlation between the two attributes: {:.3f}".format(
        float(np.corrcoef(group_a, group_b)[0, 1])))
    add("")
    add("**Verdict: {}**".format(res["verdict"]))
    add("")
    if res["masked_by_marginals"]:
        add("This is the failure mode the module exists for. Every marginal AIR")
        add("clears 0.80, so a per-attribute fairness section closes the file --")
        add("and a cell of the cross is below the screen. The disadvantage did")
        add("not disappear when averaged; it was averaged away.")
    else:
        add("No cell falls below 0.80 here, so on THIS data the cross agrees with")
        add("the marginals. That is a finding about this generator, not evidence")
        add("that the cross is unnecessary -- the machinery is what generalises,")
        add("and a benign scenario cannot demonstrate a masking effect it does")
        add("not contain.")
    add("")
    add("Cells below n = {} are reported as `insufficient` rather than given a".format(
        res["min_cell_n"]))
    add("point estimate. A 2x2 cross quarters the sample and the smallest cell")
    add("drives the verdict; an AIR of 0.62 on 40 applicants is not a finding.")
    add("")

    # ---------------------------------------------- alternative search
    add("## 2. Less-discriminatory-alternative search")
    add("")
    add("Under disparate-impact doctrine, business necessity does not end the")
    add("analysis. If a less discriminatory alternative serves the same purpose")
    add("comparably well, the original practice remains actionable. So the")
    add("question is not 'is the model justified' but 'is there a cheaper-in-")
    add("disparity model that is nearly as good'.")
    add("")

    from sklearn.metrics import roc_auc_score

    def evaluate(cols, label):
        s = _fit_score(X_tr, y_tr, X_te, cols, features)
        auc = float(roc_auc_score(y_te, s))
        cut = float(np.quantile(s, 1 - (1 - approved.mean())))
        air = fairness.adverse_impact_ratio(s < cut, group_a)["air"]
        return {"label": label, "cols": cols, "auc": auc, "air": air}

    base = evaluate(features, "full model")
    candidates = [base]
    candidates.append(evaluate(
        [c for c in features if c not in SUSPECTED_PROXIES], "proxies dropped"))
    for drop in SUSPECTED_PROXIES:
        candidates.append(evaluate([c for c in features if c != drop],
                                   "drop {} only".format(drop)))

    add("| candidate | AUC | AUC cost | AIR | AIR gain | affordable? |")
    add("|---|---|---|---|---|---|")
    for c in candidates:
        cost = base["auc"] - c["auc"]
        gain = c["air"] - base["air"]
        if c is base:
            add("| {} | {:.4f} | -- | {:.4f} | -- | (reference) |".format(
                c["label"], c["auc"], c["air"]))
            continue
        verdict = ("**yes**" if gain >= AIR_MIN_GAIN and cost <= AUC_TOLERANCE
                   else "no gain" if gain < AIR_MIN_GAIN
                   else "**gain, but over tolerance**")
        add("| {} | {:.4f} | {:+.4f} | {:.4f} | {:+.4f} | {} |".format(
            c["label"], c["auc"], cost, c["air"], gain, verdict))
    add("")
    add("Tolerances, stated rather than buried: an alternative counts only if it")
    add("improves AIR by at least **{:.3f}** and costs at most **{:.3f}** AUC."
        .format(AIR_MIN_GAIN, AUC_TOLERANCE))
    add("")

    real = [c for c in candidates[1:] if c["air"] - base["air"] >= AIR_MIN_GAIN]
    afford = [c for c in real if base["auc"] - c["auc"] <= AUC_TOLERANCE]
    if afford:
        add("**An affordable less discriminatory alternative EXISTS.** That is a")
        add("finding against the current model, and the only defensible response")
        add("is to adopt it or to explain in writing why not.")
    elif real:
        add("**An alternative reduces disparity but exceeds the stated accuracy**")
        add("**tolerance.** This is not a clean pass. The tolerance is a number I")
        add("chose, and 'our tolerance said no' is not a defence when the")
        add("tolerance was set by the party whose model is under review. It needs")
        add("an owner outside modelling.")
    else:
        add("**No alternative reduced disparity by the stated margin.** Read that")
        add("with the caveat below rather than as a clearance.")
    add("")
    add("The caveat that belongs next to every number here: baseline AIR is")
    add("{:.4f}, comfortably above the 0.80 screen, so there is very little".format(
        base["air"]))
    add("disparity for an alternative to remove. The search is demonstrated; the")
    add("scenario is benign. A fairness result on a benign scenario is evidence")
    add("about the machinery and nothing at all about the model's conduct in a")
    add("population where the disparity is real.")
    add("")
    add("## 3. What this still does not do")
    add("")
    add("- **Business-necessity documentation.** Whether `mcc_risk` is justified")
    add("  by loss experience is the lender's evidence to produce, not the")
    add("  modeller's to assert.")
    add("- **A real protected attribute.** Both overlays are fabricated here.")
    add("- **A legal conclusion.** This is the arithmetic a fair-lending review")
    add("  runs on; the review is a person's job.")

    doc = "\n".join(out)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "FAIRNESS_DEEP.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/FAIRNESS_DEEP.md")


if __name__ == "__main__":
    main()
