"""The monitoring schedule, driven over two weeks of simulated time.

    python run_schedule.py

`monitor.py` produces the report and `src/retraining.py` ranks the triggers.
Nothing ran either. A monitoring plan that executes when somebody remembers to
execute it gets run AFTER an incident, to explain it, rather than before one, to
catch it.

This drives `src/schedule.py` across fourteen days containing a real drift event,
a flapping signal, and a three-day outage of the monitoring job itself, and
counts how many times an on-call engineer would have been woken.

Writes docs/SCHEDULE.md.
"""
from __future__ import annotations

import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.schedule import (BREACHES_TO_PAGE, CADENCE_MINUTES, CLEAN_TO_RESET,
                          RETRAIN_COOLDOWN_HOURS, ScheduleState,
                          detection_delay_minutes, due, observe,
                          record_retrain, retrain_allowed)

START = datetime(2026, 8, 1, 0, 0, tzinfo=timezone.utc)
HOURS = 14 * 24
STATE = ROOT / "artifacts" / "schedule_state.json"


def alert_rate_breached(hour: int) -> bool:
    """The signal being monitored, hour by hour.

      hours 0-71    quiet
      hours 72-95   FLAPPING -- crosses the threshold every other hour. One
                    event, twelve crossings, and without hysteresis twelve pages.
      hours 96-167  quiet again
      hours 168-215 a REAL sustained drift
      hours 216+    resolved
    """
    if 72 <= hour < 96:
        return hour % 2 == 0
    if 168 <= hour < 216:
        return True
    return False


def main() -> int:
    if STATE.exists():
        STATE.unlink()
    state = ScheduleState.load(STATE)

    # The monitoring job itself is down for three days, hours 120-191. Note it
    # overlaps the start of the real drift: the outage HIDES the first day of it.
    outage = range(120, 192)

    events = []
    pages = resolutions = runs = 0
    naive_pages = 0            # what a no-hysteresis, every-run-pages job costs
    retrains = 0
    refused_retrains = 0

    for hour in range(HOURS):
        now = START + timedelta(hours=hour)
        breached = alert_rate_breached(hour)
        if breached:
            naive_pages += 1

        if hour in outage:
            continue

        d = due(state, now)
        if not d["alert_rate"]["due"]:
            continue

        runs += 1
        out = observe(state, "alert_rate", breached, now,
                      missed=d["alert_rate"]["missed"])
        if out["page_now"]:
            pages += 1
            events.append((hour, "PAGE", out["consecutive_breaches"],
                           d["alert_rate"]["missed"]))
            r = retrain_allowed(state, now)
            if r["allowed"]:
                record_retrain(state, now)
                retrains += 1
                events.append((hour, "retrain", 0, 0))
            else:
                refused_retrains += 1
                events.append((hour, "retrain REFUSED", 0, 0))
        elif out["resolved_now"]:
            resolutions += 1
            events.append((hour, "resolved", out["consecutive_clean"],
                           d["alert_rate"]["missed"]))
        elif d["alert_rate"]["missed"]:
            events.append((hour, "back after {} missed runs".format(
                d["alert_rate"]["missed"]), out["consecutive_breaches"],
                d["alert_rate"]["missed"]))

    state.save()

    L = []
    add = L.append
    add("# ML-1 — the monitoring schedule")
    add("")
    add("Generated by `run_schedule.py` over {} hours of simulated time".format(HOURS))
    add("containing a flapping signal, a real sustained drift, and a three-day")
    add("outage of the monitoring job itself.")
    add("")
    add("`monitor.py` produced the report and `src/retraining.py` ranked the")
    add("triggers. Nothing ran either — and a monitoring plan that executes when")
    add("somebody remembers to execute it gets run *after* an incident, to")
    add("explain it, rather than before one, to catch it.")
    add("")

    add("## 1. Cadence follows signal latency")
    add("")
    add("| check | cadence | needs labels | detection delay from hysteresis |")
    add("|---|---|---|---|")
    for name, mins in CADENCE_MINUTES.items():
        labels = "yes" if name == "performance" else "no"
        add("| `{}` | {} | {} | {} |".format(
            name,
            "{} min".format(mins) if mins < 1440 else "{:.0f} days".format(mins / 1440),
            labels,
            "{} min".format(detection_delay_minutes(name))
            if detection_delay_minutes(name) < 1440
            else "{:.0f} days".format(detection_delay_minutes(name) / 1440)))
    add("")
    add("`monitor.py` already ranks its signals by how fast they can possibly")
    add("fire. Running all four on one cadence throws the fast ones away, and")
    add("running the label-dependent check hourly is worse than useless — it")
    add("recomputes the same stale answer sixty times a day and teaches whoever")
    add("reads it that the number never moves.")
    add("")

    add("## 2. What the run produced")
    add("")
    add("| | |")
    add("|---|---|")
    add("| monitor runs | {} |".format(runs))
    add("| **pages** | **{}** |".format(pages))
    add("| resolutions | {} |".format(resolutions))
    add("| retrains started | {} |".format(retrains))
    add("| retrains refused by cooldown | {} |".format(refused_retrains))
    add("")
    add("| hour | event | consecutive | missed runs |")
    add("|---|---|---|---|")
    for hour, what, n, missed in events:
        add("| {} (day {}) | {} | {} | {} |".format(
            hour, hour // 24 + 1, what, n or "", missed or ""))
    add("")

    add("### Detection delay on the one event that mattered")
    add("")
    drift_start = 168
    page_hour = next((h for h, w, _n, _m in events if w == "PAGE"), None)
    if page_hour is not None:
        outage_after = len([h for h in outage if h >= drift_start])
        total = page_hour - drift_start
        add("| | hours |")
        add("|---|---|")
        add("| real drift began | {} |".format(drift_start))
        add("| page fired | {} |".format(page_hour))
        add("| **total delay** | **{}** |".format(total))
        add("| ...of which the monitoring outage | {} |".format(outage_after))
        add("| ...of which hysteresis | {} |".format(
            detection_delay_minutes("alert_rate") // 60))
        add("| ...of which cadence rounding | {} |".format(
            total - outage_after - detection_delay_minutes("alert_rate") // 60))
        add("")
        add("Worth separating, because the three have different fixes. The")
        add("hysteresis cost is a deliberate {} hours and buys the reduction in".format(
            detection_delay_minutes("alert_rate") // 60))
        add("the next table. The {} hours of outage are not a tuning question at".format(
            outage_after))
        add("all — they are the monitoring job being down, and no threshold")
        add("setting recovers them. **The outage was the dominant cost of")
        add("detection delay in this run**, which is the opposite of where")
        add("attention usually goes.")
        add("")

    add("## 3. What hysteresis bought")
    add("")
    add("| | pages |")
    add("|---|---|")
    add("| a job that pages on every breaching run | {} |".format(naive_pages))
    add("| this schedule | **{}** |".format(pages))
    add("")
    add("Hours 72-95 are one event that crosses the threshold every other hour —")
    add("twelve crossings. PSI over a rolling window does exactly this. Without")
    add("hysteresis that is twelve pages for one event, and three pages for one")
    add("event already trains the on-call to acknowledge without looking, which")
    add("is the state in which the next real page is also ignored.")
    add("")
    add("**The cost is stated rather than skipped:** requiring {} consecutive".format(
        BREACHES_TO_PAGE))
    add("breaches DELAYS detection by {} intervals — {} minutes on the hourly".format(
        BREACHES_TO_PAGE - 1, detection_delay_minutes("alert_rate")))
    add("check. That is the trade, not a free improvement.")
    add("")
    add("Firing is slower than forgiving on purpose: {} breaches to page, {}".format(
        BREACHES_TO_PAGE, CLEAN_TO_RESET))
    add("clean runs to clear. A control that forgives as slowly as it fires")
    add("stays lit long after the incident and stops meaning anything.")
    add("")

    add("## 4. A missed monitoring run is not backfilled")
    add("")
    add("**This is the opposite of SE-2's settlement catch-up, and deliberately")
    add("so.** A settlement cycle must process every missed date: the state is")
    add("cumulative and skipping one leaves a hole. Monitoring is not")
    add("cumulative. If the box was down for three days, replaying seventy-two")
    add("monitor runs pages the on-call for drift that has already resolved and")
    add("buries the current state under history. What matters is the answer now.")
    add("")
    add("So the missed runs coalesce into one — and the **count is reported**,")
    add("because *we have not monitored for three days* is itself a finding and")
    add("silently catching up conceals it.")
    add("")
    add("Note where the outage sits in this run: hours 120-191 overlap the start")
    add("of the real drift at hour 168. **The outage hid the first day of it.**")
    add("The schedule cannot recover that day; what it can do is say so, which")
    add("is why the missed count travels with the first run back.")
    add("")

    add("## 5. The cooldown the alert cannot override")
    add("")
    add("A fired trigger is a reason to *consider* retraining, not a reason to")
    add("retrain now. Two fits inside {} hours means the second trains on a".format(
        RETRAIN_COOLDOWN_HOURS))
    add("window the first already reacted to, and neither can be judged against")
    add("a clean comparison. `src/retraining.py` already declines to fire on a")
    add("*warn* for the same reason — retraining on a warn burns the clean")
    add("comparison window a page will need later.")
    add("")

    add("## What this still is not")
    add("")
    add("- **Nothing invokes it.** This is the scheduling LOGIC — what is due,")
    add("  what pages, what may retrain — and it still needs a cron entry, a")
    add("  systemd timer or an Airflow DAG to call it. That is deliberate: the")
    add("  decisions above are the part worth testing, and they are testable")
    add("  precisely because they take `now` as a parameter instead of reading")
    add("  the clock.")
    add("- **Nothing is actually paged.** There is no PagerDuty integration, so")
    add("  `page_now` is a return value rather than a phone ringing.")
    add("- **The drift here is scripted.** The event schedule is a function of")
    add("  the hour, not a real score distribution moving. `run_retraining.py`")
    add("  drives the trigger logic against real monitor output; this drives the")
    add("  cadence and hysteresis against a signal shaped to exercise them.")
    add("- **One signal is simulated.** Only `alert_rate` is driven through the")
    add("  fourteen days. The other three cadences are configured and exercised")
    add("  by the tests, not by this run.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "SCHEDULE.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/SCHEDULE.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
