"""Intersectional fairness on REAL protected attributes.

    python run_intersectional_real.py

`README.md` listed this open: "Both attributes in the intersectional analysis
are synthetic overlays constructed by this repo, so no fairness number here
describes a real population."

That is the sharpest limitation a fairness section can have. An intersectional
metric computed over attributes the repo invented measures the generator, and
the generator was written by the same person as the metric -- so a finding is a
property of one author's assumptions agreeing with themselves.

HMDA carries TWO real protected attributes on the same applicants -- race and
sex, both self-reported -- which is the configuration intersectional analysis
needs and which is genuinely hard to find. ML-3 already downloads it, so this
reads that file rather than fetching a second copy.

WHAT THIS IS AND IS NOT. The MACHINERY under test is ML-1's
(`src/intersectional.py`, `src/fairness.py`): does it find a disparity that the
marginals hide? The DECISION is HMDA's -- a mortgage approval, not a fraud
score. So this validates the analysis on real attributes and does not turn ML-1
into a lending model. Both halves are stated because conflating them would be
the more attractive claim.

Writes docs/INTERSECTIONAL_REAL.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.intersectional import format_table, intersectional_table

HMDA = (ROOT.parent / "ml3-credit-scorecard" / "data" / "hmda_de_2023.csv")
MIN_CELL = 100


def main() -> int:
    if not HMDA.exists():
        print("HMDA extract not found at {}".format(HMDA))
        print("Run ML-3's download first -- this reads that file rather than")
        print("fetching a second copy.")
        return 1

    # Load ML-3's hmda module BY PATH. Both projects have a package called
    # `src`, and ML-1's is already imported -- so a plain `from src.hmda import`
    # resolves against this repo's package and fails. Adding ML-3 to sys.path
    # would be worse than failing: it would make which module wins depend on
    # import order.
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "hmda_ml3", HMDA.parents[1] / "src" / "hmda.py")
    hmda = importlib.util.module_from_spec(spec)
    sys.modules["hmda_ml3"] = hmda
    spec.loader.exec_module(hmda)
    load, protected = hmda.load, hmda.protected

    df = protected(load())
    df = df[df.race_reported].copy()
    df = df[df.derived_sex.isin(["Male", "Female"])]

    # "Selected" is the favourable outcome: an approval.
    selected = (df.denied == 0).to_numpy().astype(int)

    # BOTH ATTRIBUTES MUST BE BINARY, and that is a real constraint of the
    # module rather than a convenience here -- `intersectional_table` iterates
    # over (0, 1) for each axis. Naming what that costs is the first finding of
    # running it on real data.
    race_minority = df.is_minority.to_numpy().astype(int)
    sex_female = (df.derived_sex == "Female").to_numpy().astype(int)

    res = intersectional_table(selected, race_minority, sex_female,
                               name_a="minority", name_b="female",
                               min_n=MIN_CELL)

    L = []
    add = L.append
    add("# ML-1 — intersectional fairness on REAL protected attributes")
    add("")
    add("Generated by `run_intersectional_real.py` on {:,} real HMDA 2023".format(
        len(df)))
    add("Delaware applications with race AND sex both self-reported.")
    add("")

    add("## Why this run exists")
    add("")
    add("`README.md` listed the sharpest limitation a fairness section can")
    add("have: *both attributes in the intersectional analysis are synthetic")
    add("overlays constructed by this repo, so no fairness number here")
    add("describes a real population.*")
    add("")
    add("An intersectional metric over invented attributes measures the")
    add("generator — and the generator was written by the same author as the")
    add("metric, so a \"finding\" is one set of assumptions agreeing with")
    add("itself. HMDA carries two real protected attributes on the same")
    add("applicants, which is the configuration this needs and is genuinely")
    add("hard to find.")
    add("")
    add("**The machinery under test is ML-1's; the decision is HMDA's** — a")
    add("mortgage approval, not a fraud score. This validates the analysis on a")
    add("real population and does not turn ML-1 into a lending model.")
    add("")

    add("## The table")
    add("")
    add("| cell | n | approval rate | ratio vs best | 95% CI | status |")
    add("|---|---|---|---|---|---|")
    for c in res["cells"]:
        ci = ("{:.3f}–{:.3f}".format(*c["ci"]) if c.get("ci") else "—")
        ratio = ("{:.4f}".format(c["ratio"])
                 if c.get("ratio") == c.get("ratio") else "—")
        add("| {} | {:,} | {:.2%} | {} | {} | {} |".format(
            c["cell"], c["n"], c["rate"], ratio, ci, c["status"]))
    add("")
    add("| marginal | rate (=1) | rate (=0) | AIR |")
    add("|---|---|---|---|")
    for m in res["marginals"]:
        add("| {} | {:.2%} | {:.2%} | **{:.4f}** |".format(
            m["attribute"], m["rate_1"], m["rate_0"], m["air"]))
    add("")

    add("## The verdict")
    add("")
    add("> {}".format(res["verdict"]))
    add("")
    failing = [c for c in res["cells"] if c["status"] == "below 0.80"]
    if res["masked_by_marginals"]:
        add("**This is the finding the module exists to produce**, and it is")
        add("now produced on real attributes rather than invented ones: a CELL")
        add("fails the 80% rule while every single-attribute AIR passes. A")
        add("fairness review that checked race and then sex would have closed")
        add("the file.")
    elif failing:
        add("Cells fail and the marginals flag it too, so the")
        add("single-attribute analysis would not have missed this one. The")
        add("intersectional view adds precision about WHERE rather than")
        add("catching something otherwise invisible.")
    else:
        add("**No cell falls below 0.80 at this operating point.** That is the")
        add("honest outcome and it is reported rather than searched past.")
        add("Intersectional disparity is a thing that CAN happen, not one that")
        add("always does, and a fairness tool that only ever reports findings")
        add("is one nobody should trust.")
        add("")
        add("What the run establishes is that the machinery produces a real")
        add("number on a real population — which is exactly what the README")
        add("said it could not.")

        # A threshold verdict of "no finding" is not the same as "no effect",
        # and reporting only the former throws away the direction the module
        # exists to detect.
        usable = [c for c in res["cells"]
                  if c.get("ratio") == c.get("ratio")]
        if usable:
            worst = min(usable, key=lambda c: c["ratio"])
            marg = [m["air"] for m in res["marginals"]
                    if m["air"] == m["air"]]
            if marg and worst["ratio"] < min(marg) - 0.005:
                add("")
                add("**But read the direction, not only the threshold.** The")
                add("worst cell (`{}`) sits at **{:.4f}** — below".format(
                    worst["cell"], worst["ratio"]))
                add("*both* marginals ({}).".format(
                    ", ".join("{:.4f}".format(m) for m in sorted(marg))))
                add("So the intersection IS worse than either attribute alone,")
                add("which is precisely the effect the module was written to")
                add("find; it simply does not cross 0.80 on this population.")
                add("")
                add("Reporting that as \"no finding\" would throw away the")
                add("direction. A threshold verdict answers *is this")
                add("actionable today*; the ratio answers *is the effect")
                add("there*, and those are different questions.")
    add("")

    add("## The constraint running it on real data exposed")
    add("")
    add("`intersectional_table` iterates over `(0, 1)` for each axis, so **both")
    add("attributes must be binary.** On real HMDA that forced race down to")
    add("minority / non-minority.")
    add("")
    add("That reduction is the exact aggregation ML-3's")
    add("`docs/HMDA_FAIR_LENDING.md` found hides a failing group: on the same")
    add("data the aggregate AIR passes at 0.8478 while four individual race")
    add("groups fail. So a binary intersectional table can report *no cell")
    add("below 0.80* on a population where a named group is being declined at")
    add("a failing rate — which is a limitation of the tool, not of the data,")
    add("and it is the kind that only shows up when the tool meets a")
    add("population with more than two of anything.")
    add("")

    add("## What this still does not license")
    add("")
    add("- **The decision is a mortgage approval.** Every caveat in")
    add("  `ml3-credit-scorecard/docs/HMDA_FAIR_LENDING.md` applies unchanged:")
    add("  no credit score, every lender in the state pooled, and a disparity")
    add("  here is an upper bound on unexplained disparity.")
    add("- **Race is self-reported and sex is partly observed.** HMDA records")
    add("  whether each was reported or inferred by the loan officer, and this")
    add("  run keeps only applications where race was reported. Sex is not")
    add("  filtered the same way, which is an inconsistency worth naming rather")
    add("  than smoothing.")
    add("- **Two attributes is not intersectionality.** Real intersectional")
    add("  analysis spans more axes than a 2-D table has room for, and the")
    add("  cell-size floor is what stops it going further — every axis added")
    add("  divides the population again.")
    add("- **ML-1's own fraud model is still fitted on generated data.** This")
    add("  run validates the ANALYSIS on a real population. The model that")
    add("  analysis is usually pointed at has not changed.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "INTERSECTIONAL_REAL.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/INTERSECTIONAL_REAL.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
